### ISSUE TITLE
Table with only a PK and no others fields become non-persistent valueObject

### ISSUE THREAD

**Issue by forhanp** [vertigo-io/vertigo#109]
With a model containing 3 tables : 
- 2 with several fields, (Tables A and B)
- 1 associated to the 2 others and containing only a PK field by itself. (Table C)

No others specific properties set (typically no stereotype).
Table A and B implements Entity
Table C implements DtObject

Therefore, table C has no DAO generated and is considered has non-persistent object.

This was discovered using Enterprise Architect. No visible differences in the xmi file for the definition of PK in table C.

**Comment by NPi2Loup** [comment]
When such empty table are usefull ?
