### ISSUE TITLE
extension of ROWNUM use in KSP select

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [vertigo-io/vertigo#113]
As domain for field can now marked as multiple, it should be possible to write the following in KSP task associated with select

id in (#CRITERE.IDS.ROWNUM#)

with the DtObject Critere having a field IDS whose domain is marked as multiple

**Comment by mlaroche** [comment]
Similar to issue #42 and no decision was taken yet

**Comment by NPi2Loup** [comment]
The `Where In` handler in Tasks now supports List of primitive and list of object. 
These two cases were simple to use andsimple to understand.

We decided to limit usage to this solution : only one level. 
This limit the object's tree depth to one. 
The API of DAO are nearer to buisness case : input attributes are flat and visible in api.
