### ISSUE TITLE
FileAttachment.inline

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#140]
Dans certains projets, il y a besoin selon le service Vega d'utiliser le code http "inline;" à la place d' "attachment;" dans la classe `VFileUtil`.

Il faudrait que `WebServiceDefinition` gère ce cas.
Et si cela convient pour cela, la nouvelle annotation `FileAttachment` pourrait avoir un attribut `inline` (false par défaut).

**Comment by mlaroche** [comment]
Hello,

"inline" is the default value for content disposition. see : (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body) 

If you need the file to be displayed by the brower just remove the `@FileAttachment` annotation on your webservice.

Can you provider a working example where you need to force the 'inline' header?

**Comment by evernat** [comment]
Here is my example :
```java
@PathPrefix("/seance")
public class SeanceWebServices implements WebServices {
    @Inject
    private SeanceServices seanceServices;

    @GET("/downloadDemande/{demandeId}")
    public VFile downloadDemande(@PathParam("demandeId") final Long demandeId) {
        return seanceServices.downloadDemande(demandeId);
    }
}
```
This is Vertigo 1.1.3, from 0.9.1 on the way to 2.0.0.
It seems to me that Vertigo will always add an attachment Content-Disposition in this case.
The project wants to have an inline Content-Disposition most of the time and it probably does not want to remove the http headers (the name in the Content-Disposition, the size and the date of the file may be important too).

And a question. When should `@FileAttachment` be used in 2.0.0 ?
I do not see it currently in the [documentation](https://vertigo-io.github.io/vertigo-docs/#/advanced/vega) or in the [migration guide](https://github.com/vertigo-io/vertigo/wiki/Vertigo-Migration-Guide).

**Comment by mlaroche** [comment]
Hello,

My mistake in Vertigo the default behaviour is attachement in WebserviceDefinition
To use inline (aka nothing in the header) you must annotate your webservice method with `@FileAttachment(false)` 

Semantic isn't ideal we will take your remark into account in future releases.
Thanks for your contribution!

Can you confirm that the solution I gave you work as expected ?

**Comment by evernat** [comment]
en effet, le header est ok avec `@FileAttachment(false)` en vertigo 2.
Merci.
