### ISSUE TITLE
SwaggerApiBuilder & TypeVariable

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#142]
Dans `SwaggerApiBuilder`, certains projets ajoutent
`&& !(((ParameterizedType) type).getActualTypeArguments()[0] instanceof TypeVariable<?>)` 
après `&& !(((ParameterizedType) type).getActualTypeArguments()[0] instanceof WildcardType)`.

La raison indiquée est :
> Correction vertigo qui a du mal sur les types paramétrés pour la construction de la swagger API.

**Comment by NPi2Loup** [comment]
Please provided an use case or a description of your issue.

**Comment by evernat** [comment]
Je ne suis pas certain mais il s'agit peut-être de la méthode suivante (avec les fichiers joints) :
```java
public class IndexSearchWebServices implements WebServices {
        /**
         * Effectue une recherche dans l'index ES.
         *
         * @param top nombre max d'éléments.
         * @param sortFieldName nom du champ sur lequel trier.
         * @param sortDesc sens de tri descendant ou non.
         * @param skip nombre de résultats à passer.
         * @param searchCriteria critère de recherche.
         * @param facet facettes selectionnées.
         * @param clusteringFacetName groupes de facette.
         *
         * @return le résultat.
         */
        @POST("/search")
        @AnonymousAccessAllowed
        public CustomFacetedQueryResult search(
                        @QueryParam("top") final Integer top,
                        @QueryParam("sortFieldName") final String sortFieldName,
                        @QueryParam("sortDesc") final boolean sortDesc,
                        @QueryParam("skip") final int skip,
                        @InnerBodyParam("criteria") final Map<String, Object> searchCriteria,
                        @InnerBodyParam("facets") final UiSelectedFacets facet,
                        @InnerBodyParam("group") final String clusteringFacetName) {
...
        }
}
```
[CustomFacet.txt](https://github.com/vertigo-io/vertigo/files/3728543/CustomFacet.txt)
[CustomFacetedQueryResult.txt](https://github.com/vertigo-io/vertigo/files/3728575/CustomFacetedQueryResult.txt)

**Comment by evernat** [comment]
Il y a sûrement plus simple pour des TypeVariable. On peut essayer avec un code du genre :
```java
@POST("/test")
public <T extends Number> void test(T from, T to) {
...
}
```

**Comment by NPi2Loup** [comment]
Thanks for your tes case. 
We fixed how we check supported parameterizedType; Your cas should work.
