### ISSUE TITLE
SwaggerWebServices & localhost

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#143]
Dans `SwaggerWebServices`, certains projets ajoutent le code suivant au début de la méthode `getSwapperApi` :
```java
		if (!getAdressesLocales().contains(request.getRemoteAddr())) {
			return new HashMap<>();
		}
		...
```

```java
	private Set<String> getAdressesLocales() {
		final Set<String> adressesLocales = new HashSet<>();

		try {
			adressesLocales.add(InetAddress.getLocalHost().getHostAddress());
			for (final InetAddress inetAddress : InetAddress.getAllByName("localhost")) {
				adressesLocales.add(inetAddress.getHostAddress());
			}
		} catch (final UnknownHostException e) {
			throw new RuntimeException("Impossible de récupérer les adresses locales.");
		}

		return adressesLocales;
	}
```

C'est capilotracté et pas forcément performant en l'état (a minima, il pourrait y avoir un cache de `getAdressesLocales()` en attribut).

Il n'y a pas de raison indiquée pour cet ajout.
Mais il s'agit peut-être de ne pas exposer l'url de swagger api par contrainte de sécurité, sauf (en développement) depuis localhost ?

**Comment by mlaroche** [comment]
Please provide your use case or the issue you encounter but not just code. Maybe contact the project team that wrote this code to know the desired behaviour, and we will try to help you.

**Comment by evernat** [comment]
Il me semble que l'endpoint swagger est utilisé ici pour de la documentation. Il liste tous les services REST disponibles et les paramètres possibles. Par défaut, il est déclaré public (accès anonyme) et quelle que soit l'ip du client. Dis-moi si j'ignore un truc.

D'un point de vue sécurité, cela augmente la surface d'attaque et cela facilite le travail d'un attaquant en lui offrant sur un plateau toutes les possibilités d'attaques à sa disposition.
Il existe même [des outils à la portée d'un enfant](https://smartbear.com/product/ready-api/secure/overview/) pour utiliser directement ces informations et déclencher toutes les attaques possibles jusqu'à trouver des failles.
Il ne paraît pas étonnant qu'un développeur bien formé ou qu'un RSSI s'inquiète de cela (et il y a souvent des RSSI prudents voir paranoïaques qui imposent des contraintes).
Est-ce que je me trompe ?

Pour prendre en compte cette inquiétude ou cette contrainte, il me semble utile de prévoir une réponse ou même une bonne pratique. Par exemple, permettre de restreindre cet endpoint à localhost (ou à une regexp d'ip éventuellement) selon un paramètre ou selon un WebServiceHandlerPlugin prêt à l'emploi serait un début de réponse.

Est-ce que ce use case te convient ? Si non, quel serait le code pour faire cela sans réécrire la classe Vertigo s'il-te-plaît ?

**Comment by mlaroche** [comment]
The webapp is not responsible securing and filtering webservices routes.
Securing and filtering webservices routes **must** (this is not a choice) be handled by a dedicated solution outside of the scope of the webapp : for example a WAF (Web Application Firewall), a web-server (nginx, apache...), network hardware solutions, etc...
We also encourage the usage of APIManagement solutions that offer suitable security features.
