### ISSUE TITLE
FileStorePlugin & FileActionSave, FileActionDelete

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#144]
Lors de l'écriture d'une implémentation de FileStorePlugin dans un projet, il est utile de pouvoir utiliser les classes FileActionSave et FileActionDelete pour ne pas les réécrire à l'identique.
Il faudrait les mettre `public`, sinon les projets vont écrire leur classe d'implémentation du FileStorePlugin dans le package io.vertigo.dynamo.plugins.store.filestore.fs.

**Comment by mlaroche** [comment]
Hello,
`FileActionSave` and `FileActionDelete` are not in the public API. The public API is the `FileStore` provided by the `StoreManager`

If a project needs to build it's own plugin it's a better design if it controls the process as a whole, especially concerning plugins that handle external resources...

Concerning your point `sinon les projets vont écrire leur classe d'implémentation du FileStorePlugin dans le package io.vertigo.dynamo.plugins.store.filestore.fs.` it's not the way to go, espacially with Java9+ module system that doesn't allow it.

Why your project needs to provide a specific plugin to store files? Can you describe the use case it covers ?
