### ISSUE TITLE
TempFile.deleteOnExit()

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#145]
La classe TempFile hérite de File et appelle deleteOnExit() dès son instanciation.
Ce n'est pas une bonne idée à mon humble avis pour plusieurs raisons :
- deleteOnExit() est efficace bien tard par rapport au besoin. Pour les applications sur des serveurs, cela peut être des semaines ou des mois plus tard. Les fichiers temporaires peuvent avoir rempli le disque dur ou laissé des données confidentielles sur le disque dur trop longtemps.
- cela ne garantie pas que le fichier soit effacé (kill -9 contourne la procédure d'exit et ne peut effacer ces fichiers, qui peuvent contenir des données confidentielles et qui à ma connaissance restent ad-vitam æternam)
- au fur et à mesure des instanciations de TempFile, une fuite mémoire progresse dans la JVM.

Je suggère :
1. enlever les deleteOnExit() dans les constructeurs. Le deleteOnExit() dans finalize() est suffisant pour cela et au moins il n'est appelé que si delete() n'a pas fonctionné.
2. remplacer le deleteOnExit() restant dans finalize() par une gestion de List<String> globale à la webapp, thread-safe et purgée régulièrement (ou au pire lors de l'arrêt de la webapp ce qui ne serait pas forcément mieux que deleteOnExit()).

**Comment by NPi2Loup** [comment]
This issue was already fixed. There is a deamon since 0.9.1.
Which version are you using ?

**Comment by evernat** [comment]
Sorry, this is version 1.1.3 at the moment, in the middle of the journey from 0.9.1 to 2.0.0.

Note that the last point is not fixed. There is still deleteOnExit() in constructors :
https://github.com/vertigo-io/vertigo/blob/develop/vertigo-core/src/main/java/io/vertigo/util/TempFile.java

Post-scriptum: my browser understands French, not English ;-)
