### ISSUE TITLE
Les fichiers de configuration ne sont pas lus dans le classpath

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo#150]
https://github.com/vertigo-io/vertigo/blob/2263ee73b12bd4d455500afeca543204c3e89e97/vertigo-core/src/main/java/io/vertigo/core/node/config/yaml/YamlAppConfigBuilder.java#L323

Càd :
```java
		try {
			return new URL(fileName);
		} catch (final MalformedURLException e) {
			//Si fileName non trouvé, on recherche dans le classPath
			final URL url = relativeRootClass.getResource(fileName);
```

Bonne idée qui pourrait aider pour pouvoir lancer Namespace2Java depuis un répertoire ou depuis son parent, sauf que MalformedURLException n'est pas lancée si le fichier n'existe pas.

**Comment by NPi2Loup** [comment]
Please write your issues in english.

The config file support two usages : 
- url : specify a protocol
- classPath ; don't specify protocol

**Comment by evernat** [comment]
OK, right. It works as expected without a protocol.
That is after changing from `boot.applicationConfiguration=file:serveur/src/main/resources/mda/mda.xml` to `boot.applicationConfiguration=/mda/mda.xml`.
So closing as not a bug.

Unfortunately for me, targetGenDir in mda.xml is relative to the current working directory of the mvn command and not relative to the Maven module where NameSpace2JavaOld is declared.
So it seems to me that we can't have source generation in the right folder either from the child Maven module or from the parent Maven module: it can work from only one module depending on config and not both ways. But that's another issue.
