### ISSUE TITLE
[WhereInProcessor] Please allow the 'in' clause to take values from a Dto Object

### ISSUE THREAD

**Issue by durandx** [vertigo-io/vertigo#42]
I cannot use a list filtered in a criteria. For exemple, the following statement is not valid, forcing me to remove the filtered list outside the criteria Dto Object:

```
IN (#DT_STRUCTURE_CRITERIA.STRUCTURES.ROWNUM.KEY#)
```

Please allow the usage of IN clause to take values from a Dto Object.

**Comment by NPi2Loup** [comment]
In order to keep DtObject persistent, they should be flat.
Although it's possible to design a DtObject with some of these type of fields, 
Vertigo doesn't support fully this usage. You should use separate task parameter.

Your use case is similar to issue #41, and no decision was taken yet.

**Comment by NPi2Loup** [comment]
The `Where In` handler in Tasks now supports List of primitive and list of object. 
These two cases were simple to use andsimple to understand.

We decided to limit usage to this solution : only one level. 
This limit the object's tree depth to one. 
The API of DAO are nearer to buisness case : input attributes are flat and visible in api.
